# Hamoye Stage C 

In [1]:
# import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
#import data set
df= pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/00471/Data_for_UCI_named.csv')

In [4]:
df.shape

(10000, 14)

In [3]:
df.head()

tau1      tau2      tau3      tau4        p1        p2        p3  \
0  2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1  9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2  8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3  0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4  3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   

         p4        g1        g2        g3        g4      stab     stabf  
0 -1.723086  0.650456  0.859578  0.887445  0.958034  0.055347  unstable  
1 -1.255012  0.413441  0.862414  0.562139  0.781760 -0.005957    stable  
2 -0.920492  0.163041  0.766689  0.839444  0.109853  0.003471  unstable  
3 -0.997374  0.446209  0.976744  0.929381  0.362718  0.028871  unstable  
4 -0.554305  0.797110  0.455450  0.656947  0.820923  0.049860  unstable

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   tau1    10000 non-null  float64
 1   tau2    10000 non-null  float64
 2   tau3    10000 non-null  float64
 3   tau4    10000 non-null  float64
 4   p1      10000 non-null  float64
 5   p2      10000 non-null  float64
 6   p3      10000 non-null  float64
 7   p4      10000 non-null  float64
 8   g1      10000 non-null  float64
 9   g2      10000 non-null  float64
 10  g3      10000 non-null  float64
 11  g4      10000 non-null  float64
 12  stab    10000 non-null  float64
 13  stabf   10000 non-null  object 
dtypes: float64(13), object(1)
memory usage: 1.1+ MB


In [7]:
df.describe()

tau1          tau2          tau3          tau4            p1  \
count  10000.000000  10000.000000  10000.000000  10000.000000  10000.000000   
mean       5.250000      5.250001      5.250004      5.249997      3.750000   
std        2.742548      2.742549      2.742549      2.742556      0.752160   
min        0.500793      0.500141      0.500788      0.500473      1.582590   
25%        2.874892      2.875140      2.875522      2.874950      3.218300   
50%        5.250004      5.249981      5.249979      5.249734      3.751025   
75%        7.624690      7.624893      7.624948      7.624838      4.282420   
max        9.999469      9.999837      9.999450      9.999443      5.864418   

                 p2            p3            p4            g1            g2  \
count  10000.000000  10000.000000  10000.000000  10000.000000  10000.000000   
mean      -1.250000     -1.250000     -1.250000      0.525000      0.525000   
std        0.433035      0.433035      0.433035      0.274256      0.274255   
min       -1.999891     -1.999945     -1.999926      0.050009      0.050053   
25%       -1.624901     -1.625025     -1.624960      0.287521      0.287552   
50%       -1.249966     -1.249974     -1.250007      0.525009      0.525003   
75%       -0.874977     -0.875043     -0.875065      0.762435      0.762490   
max       -0.500108     -0.500072     -0.500025      0.999937      0.999944   

                 g3            g4          stab  
count  10000.000000  10000.000000  10000.000000  
mean       0.525000      0.525000      0.015731  
std        0.274255      0.274255      0.036919  
min        0.050054      0.050028     -0.080760  
25%        0.287514      0.287494     -0.015557  
50%        0.525015      0.525002      0.017142  
75%        0.762440      0.762433      0.044878  
max        0.999982      0.999930      0.109403

In [5]:
df.isna().sum()

tau1     0
tau2     0
tau3     0
tau4     0
p1       0
p2       0
p3       0
p4       0
g1       0
g2       0
g3       0
g4       0
stab     0
stabf    0
dtype: int64

In [8]:
# % of values present
df['stabf'].value_counts() / df.shape[0]*100

unstable    63.8
stable      36.2
Name: stabf, dtype: float64

In [9]:
df.drop('stab', axis=1, inplace=True)

In [10]:
df.head()

tau1      tau2      tau3      tau4        p1        p2        p3  \
0  2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1  9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2  8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3  0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4  3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   

         p4        g1        g2        g3        g4     stabf  
0 -1.723086  0.650456  0.859578  0.887445  0.958034  unstable  
1 -1.255012  0.413441  0.862414  0.562139  0.781760    stable  
2 -0.920492  0.163041  0.766689  0.839444  0.109853  unstable  
3 -0.997374  0.446209  0.976744  0.929381  0.362718  unstable  
4 -0.554305  0.797110  0.455450  0.656947  0.820923  unstable

In [11]:
#splitting of features and fixing target variable
x = df.drop('stabf', axis=1)
y = df['stabf']

In [12]:
#split the data test size of 20
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size= 0.2 , random_state= 1 )

In [13]:
#Scaling dataset using standard scaler
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
train_df = scaler.fit_transform(x_train)
train_df = pd.DataFrame(train_df, columns=x_train.columns)

In [14]:
train_df.head()

tau1      tau2      tau3      tau4        p1        p2        p3  \
0  0.367327 -0.986042  0.650447  1.547527 -0.291490  0.061535  1.293862   
1 -0.064659  0.089437  1.035079 -1.641494  0.619865 -0.067235 -1.502925   
2 -1.467850  1.298418 -0.502536  1.166046 -0.180521  0.490603  0.682560   
3  0.820081  0.529920  1.299657 -1.141975 -0.812854 -0.763632  1.521579   
4  0.665424 -1.425627  0.312300  0.919137 -1.614296  0.760315  1.422019   

         p4        g1        g2        g3        g4  
0 -0.845074  0.160918  0.339859  0.585568  0.492239  
1  0.486613 -0.293143 -1.558488  1.429649 -1.443521  
2 -0.855302  1.399350  1.451534 -1.045743  0.492489  
3  0.658780 -0.958319  1.361958  1.604140  0.275303  
4  0.639243  1.676895  0.695660  1.137504 -1.312575

In [17]:
test_df = scaler.fit_transform(x_test)
test_df = pd.DataFrame(test_df, columns=x_test.columns)

In [18]:
test_df.head()

tau1      tau2      tau3      tau4        p1        p2        p3  \
0  0.592163 -0.420565  1.472472  1.093036  0.426786 -1.504594 -0.792677   
1  0.199183  0.364543 -0.190076 -0.518473 -0.229402 -1.071766  0.427103   
2 -1.086035 -0.321834 -0.873505  0.011761 -0.977094  0.094896  0.813041   
3 -0.087014 -1.113357  0.361518 -1.684316  0.792280 -1.649041  0.410662   
4  0.873004  1.425833  0.080476  1.681022 -0.154247 -0.024315 -0.197525   

         p4        g1        g2        g3        g4  
0  1.600201 -0.925703  1.175287 -1.492644  1.086291  
1  1.052337 -1.655910 -0.395949  1.412703  1.227535  
2  0.751381  1.450284 -1.444370  0.654216 -1.679799  
3 -0.084473  0.066085 -1.679450 -0.349573  1.057439  
4  0.485988  0.119716 -1.475773  0.957057 -0.817608

# Random Forest

In [63]:
# Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
forest = RandomForestClassifier(n_estimators=100)
forest.fit(train_df, y_train)

RandomForestClassifier()

In [64]:
y_pred_rf = forest.predict(train_df)

In [65]:
y_pred_rf

array(['unstable', 'unstable', 'unstable', ..., 'unstable', 'unstable',
       'stable'], dtype=object)

In [66]:
#Confusion Matrix for Random Forest
from sklearn.metrics import recall_score, accuracy_score, precision_score, f1_score, confusion_matrix
matrix = confusion_matrix(y_true=y_test, y_pred=y_pred_rf, labels=[ 'stable', 'unstable' ])
matrix

ValueError: Found input variables with inconsistent numbers of samples: [2000, 8000]

In [ ]:
#Random Forest Accuracy
accuracy = accuracy_score(y_test,y_pred_rfc)
print(f"Accuracy: {round(accuracy,4)}")

# XGBoost

In [25]:
#xgboost classifier
from xgboost import XGBClassifier
xgb = XGBClassifier(random_state=1)
xgb.fit(train_df, y_train)

c:\users\sonali\appdata\local\programs\python\python39\lib\site-packages\xgboost\sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[21:50:22] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=8, num_parallel_tree=1, random_state=1,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [28]:
ypred_xgb = xgb.predict(test_df)

In [32]:
#Confusion Matrix for XGBoost
cnf_mat_XGB = confusion_matrix(y_true=y_test, y_pred=ypred_xgb, labels=[ 'stable', 'unstable' ])
cnf_mat_XGB

array([[ 647,   65],
       [  43, 1245]], dtype=int64)

In [33]:
#XGBoost Accuracy
accuracy = accuracy_score(y_test,ypred_xgb)
print(f"Accuracy: {round(accuracy,5)}")

Accuracy: 0.946


# Light GBM

In [35]:
## Lightgbm Model
import lightgbm as lgb
lgb_clf = lgb.LGBMClassifier(random_state=1)
lgb_clf.fit(train_df, y_train)
ypred_lgb = lgb_clf.predict(test_df)

In [36]:
#Confusion Matrix for Light GBM
cnf_mat_LGBM = confusion_matrix(y_true=y_test, y_pred=y_pred_lgb, labels=[ 'stable', 'unstable' ])
cnf_mat_LGBM

array([[ 636,   76],
       [  51, 1237]], dtype=int64)

In [37]:
#Lightgbm Accuracy
accuracy = accuracy_score(y_test,ypred_lgb)
print(f"Accuracy: {round(accuracy,4)}")

Accuracy: 0.9365


# Extra Trees Classifier

In [42]:
from sklearn.ensemble import ExtraTreesClassifier
ETC = ExtraTreesClassifier(random_state = 1)
ETC.fit(train_df, y_train)
y_predetc = ETC.predict(test_df)

In [43]:
#Confusion Matrix for Extra Tree Classifier
cnf_mat_ETC = confusion_matrix(y_true=y_test, y_pred=y_predetc, labels=[ 'stable', 'unstable' ])
cnf_mat_ETC

array([[ 602,  110],
       [  38, 1250]], dtype=int64)

In [45]:
#Extra Tree Classifier Accuracy
accuracy = accuracy_score(y_test,y_predetc)
print(f"Accuracy: {round(accuracy,4)}")

Accuracy: 0.926


# Tuning Parameters

In [49]:
n_estimators = [50,100,300,500,1000] 
min_samples_split = [2,3,5,7,9] 
min_samples_leaf = [1,2,4,6,8] 
max_features = ['auto','sqrt','log2',None] 
hyperparameter_grid = {'n_estimators':n_estimators,
                       'min_samples_leaf':min_samples_leaf,
                       'min_samples_split':min_samples_split,
                       'max_features':max_features}

# Randomized CV Search

In [50]:
from sklearn.model_selection import RandomizedSearchCV

In [53]:
search = RandomizedSearchCV(estimator = ETC,param_distributions=hyperparameter_grid,random_state=1)
search = search.fit(train_df, y_train)

In [54]:
search.best_params_

{'n_estimators': 1000,
 'min_samples_split': 2,
 'min_samples_leaf': 8,
 'max_features': None}

# New Classifier using Extra Trees

In [55]:
n_classifier = ExtraTreesClassifier(random_state=1,n_estimators = 1000,
                                       min_samples_leaf= 8,max_features=None,
                                       min_samples_split=2)
n_classifier.fit(train_df, y_train)
pred_new = n_classifier.predict(test_df)

In [56]:
accuracy = accuracy_score(y_test,pred_new)
print(f"Accuracy: {round(accuracy,4)}")

Accuracy: 0.9285


# Feature Importance

In [57]:
fea_imp = search.best_estimator_.feature_importances_
fea_imp

array([0.13723975, 0.1405075 , 0.13468029, 0.13541676, 0.00368342,
       0.00533686, 0.00542927, 0.00496249, 0.10256244, 0.10757765,
       0.11306268, 0.10954089])

In [62]:
sorted(zip(fea_imp,x))

[(0.003683422151688322, 'p1'),
 (0.004962486591192238, 'p4'),
 (0.005336864710946151, 'p2'),
 (0.005429268421191957, 'p3'),
 (0.10256244080927947, 'g1'),
 (0.10757764577478764, 'g2'),
 (0.10954089174337298, 'g4'),
 (0.11306267999167334, 'g3'),
 (0.13468028520386593, 'tau3'),
 (0.1354167630909727, 'tau4'),
 (0.13723974766109256, 'tau1'),
 (0.14050750384993677, 'tau2')]

In [60]:
max(sorted(zip(fea_imp,x)))

(0.14050750384993677, 'tau2')

In [61]:
min(sorted(zip(fea_imp,x)))

(0.003683422151688322, 'p1')